[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/login"
  to = "/.netlify/functions/login"
  status = 200
  force = true

[[redirects]]
  from = "/mfa"
  to = "/.netlify/functions/mfa"
  status = 200
  force = true
